name: Deploy Node on EC@ with Terraform
on:
  push:
    branches:
      - master
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_KEY_ID: ${{secrets.AWS_SECRET_KEY_ID}}
  AWS_SSH_KEY_PUBLIC: ${{secrets.AWS_SSH_KEY_PUBLIC}}
  AWS_SSH_KEY_PVT: ${{secrets.AWS_SSH_KEY_PVT}}
  AWS_TF_STATE_BUCKET_NAME: ${{secrets.AWS_TF_STATE_BUCKET_NAME}}
  AWS_REGION: ap-south-1
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v2
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./infrastructure/terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan -var="access_key=$AWS_ACCESS_KEY_ID" -var="secret_key=$AWS_SECRET_KEY_ID" -var="region=ap-south-1" -var="public_key=$AWS_SSH_KEY_PUBLIC" -var="private_key=$AWS_SSH_KEY_PVT" -var="key_name=deployer-key" -out=PLAN
        working-directory: ./infrastructure/terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply PLAN
        working-directory: ./infrastructure/terraform
